services:
  app:
    image: ghcr.io/zlocate/whitelist-russia-subscription:cto-add-docker-ghcr-pipeline
    container_name: whitelist-russia-subscription
    build: .
    ports:
      - "8080:8080"
    volumes:
      - rjsxrd_data:/root/rjsxrd
    restart: unless-stopped
volumes:
  rjsxrd_data:
